# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  dapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test


# Store production database in the storage/ directory, which by default
# is mounted as a persistent Docker volume in config/deploy.yml.
production:
  primary:
    adapter: postgresql
    database: <%= ENV['DATABASE_URL'] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
  cache:
    adapter: postgresql
    database: storage/production_cache
    migrations_paths: db/cache_migrate
  queue:
    adapter: postgresql
    database: storage/production_queue
    migrations_paths: db/queue_migrate
  cable:
    adapter: postgresql
    database: storage/production_cable
    migrations_paths: db/cable_migrate

